default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tech_job_development

test:
  <<: *default
  database: tech_job_test

production:
  primary: &primary_production
    <<: *default
    database: tech_job_production
    username: tech_job
    password: <%= ENV["TECH_JOB_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tech_job_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tech_job_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tech_job_production_cable
    migrations_paths: db/cable_migrate
